SilverStripe\MimeValidator\MimeUploadValidator:
  MimeTypes:
    svg:
      - "image/svg+xml"
      - "image/svg"

SilverStripe\Assets\File:
  allowed_extensions:
    - svg

App\Team\TeamMember:
  extensions:
    - PurpleSpider\BasicGalleryExtension\PhotoGalleryExtension
  gallery-title: Galerie
  gallery-cms-tab: Galerie
  content-cms-tab: Top Content

App\Elements\FAQItem:
  extensions:
    - PurpleSpider\BasicGalleryExtension\PhotoGalleryExtension
  gallery-title: Galerie
  gallery-cms-tab: Galerie
  content-cms-tab: Top Content

App\Elements\TimelineItem:
  extensions:
    - PurpleSpider\BasicGalleryExtension\PhotoGalleryExtension
  gallery-title: Galerie
  gallery-cms-tab: Galerie
  content-cms-tab: Top Content

Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - App\Extensions\CustomSiteConfig

App\FleaMarket\FleaMarketProduct:
  extensions:
    - PurpleSpider\BasicGalleryExtension\PhotoGalleryExtension
  gallery-title: Galerie
  gallery-cms-tab: Galerie
  content-cms-tab: Top Content

App\Wiki\Show:
  extensions:
    - PurpleSpider\BasicGalleryExtension\PhotoGalleryExtension
    - App\Wiki\WikiSlugExtension
  gallery-title: Galerie
  gallery-cms-tab: Galerie
  content-cms-tab: Top Content

App\Wiki\Location:
  extensions:
    - PurpleSpider\BasicGalleryExtension\PhotoGalleryExtension
    - App\Wiki\WikiSlugExtension
  gallery-title: Galerie
  gallery-cms-tab: Galerie
  content-cms-tab: Top Content

App\Wiki\Artefact:
  extensions:
    - PurpleSpider\BasicGalleryExtension\PhotoGalleryExtension
    - App\Wiki\WikiSlugExtension
  gallery-title: Galerie
  gallery-cms-tab: Galerie
  content-cms-tab: Top Content

App\Wiki\Character:
  extensions:
    - PurpleSpider\BasicGalleryExtension\PhotoGalleryExtension
    - App\Wiki\WikiSlugExtension
  gallery-title: Galerie
  gallery-cms-tab: Galerie
  content-cms-tab: Top Content


App\Wiki\MediaProject:
  extensions:
    - App\Wiki\WikiSlugExtension

App\Wiki\WikiMusic:
  extensions:
    - App\Wiki\WikiSlugExtension

SilverStripe\LinkField\Models\Link:
  extensions:
    - App\Extensions\LinkExtension
